/**
 * Created by chenqilong on 2018/9/16.
 */
export const OPEN_POSITION_POPPER = 'OPEN_POSITION_POPPER';
export const CLOSE_POSITION_POPPER = 'CLOSE_POSITION_POPPER';
export const CHANGE_CURRENT_CITY = "CHANGE_CURRENT_CITY";
export const CHANGE_HOUSE_INFO_BY_CONDITION = "CHANGE_HOUSE_INFO_BY_CONDITION";
export const INIT_IPFS_UTILS = "INIT_IPFS_UTILS";
export const CHANGE_SHOW_HOUSE_INFO_COUNT = "CHANGE_SHOW_HOUSE_INFO_COUNT";